[package]
name = "sport_matcher"
version = "0.1.0"
authors = ["toni"]

[dependencies]
rocket = "0.4"
rocket_codegen = "0.4"
rocket_contrib = "0.4"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
rand = "0.6"
