[package]
name = "sport_matcher"
version = "0.1.0"
authors = ["A.bozzanoschwedhel"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
serde_derive = "1.0.71"
serde = "1.0.71"
rand = "0.5.5"